name: Feature Request
description: Suggest an addition or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What are you trying to do that isn't currently possible?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: spec-ref
    attributes:
      label: Spec reference (if applicable)
      description: Section of EMV QRCPS this relates to.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
